version: 0.0
os: linux
files:
  - source: app.zip
    destination: home/smurl

permissions:
  - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu