version: 0.0
os: linux
files:
  - source: app.zip
    destination: ~/smurl

permissions:
  - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu
      
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: after_install.sh
      runas: ubuntu